unstable_features = true
control_brace_style = "ClosingNextLine"
enum_discrim_align_threshold = 20
fn_single_line = true
group_import = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 100
newline_style = "Unix"
reorder_impl_items = true
struct_field_align_threshold = 5
style_edition = "2021"
tab_spaces = 4
use_small_heuristics = "Max"
# fn_call_width=60
attr_fn_like_width=80
struct_lit_width=18
struct_variant_width=35
array_width=60
# chain_width=60
single_line_if_else_max_width=50
single_line_let_else_max_width=50